// ─── PETIT TEHILIM DU JOUR (rotation des 30 psaumes les plus courts) ────────
// Textes traditionnels du Livre des Psaumes (domaine public)
// Sélectionnés parmi les plus courts en nombre de mots/versets

export const TEHILIM_JOUR = [
  {
    numero: 117,
    titre: "Hallélou Et Adonaï",
    hebreu: `הַלְלוּ אֶת יְהֹוָה כׇּל גּוֹיִם, שַׁבְּחוּהוּ כׇּל הָאֻמִּים. כִּי גָבַר עָלֵינוּ חַסְדּוֹ, וֶאֱמֶת יְהֹוָה לְעוֹלָם, הַלְלוּיָה.`,
    francais: `Louez l'Éternel, vous toutes les nations, célébrez-Le, vous tous les peuples. Car Sa bonté envers nous est grande, et la fidélité de l'Éternel dure à jamais. Louez l'Éternel !`,
  },
  {
    numero: 131,
    titre: "Shir HaMaalot LéDavid",
    hebreu: `שִׁיר הַמַּעֲלוֹת לְדָוִד: יְהֹוָה לֹא גָבַהּ לִבִּי וְלֹא רָמוּ עֵינַי, וְלֹא הִלַּכְתִּי בִּגְדֹלוֹת וּבְנִפְלָאוֹת מִמֶּנִּי. אִם לֹא שִׁוִּיתִי וְדוֹמַמְתִּי, נַפְשִׁי כְּגָמֻל עֲלֵי אִמּוֹ, כַּגָּמֻל עָלַי נַפְשִׁי. יַחֵל יִשְׂרָאֵל אֶל יְהֹוָה, מֵעַתָּה וְעַד עוֹלָם.`,
    francais: `Chant des montées, de David. Éternel, mon cœur n'est pas hautain, et mes yeux ne sont pas arrogants ; je ne m'occupe pas de choses trop grandes pour moi. Mais je me suis calmé et tenu tranquille, comme un enfant sevré contre sa mère. Qu'Israël espère en l'Éternel, dès maintenant et à jamais.`,
  },
  {
    numero: 133,
    titre: "Hiné Ma Tov",
    hebreu: `שִׁיר הַמַּעֲלוֹת לְדָוִד: הִנֵּה מַה טּוֹב וּמַה נָּעִים, שֶׁבֶת אַחִים גַּם יָחַד. כַּשֶּׁמֶן הַטּוֹב עַל הָרֹאשׁ, יֹרֵד עַל הַזָּקָן זְקַן אַהֲרֹן, שֶׁיֹּרֵד עַל פִּי מִדּוֹתָיו. כְּטַל חֶרְמוֹן, שֶׁיֹּרֵד עַל הַרְרֵי צִיּוֹן, כִּי שָׁם צִוָּה יְהֹוָה אֶת הַבְּרָכָה, חַיִּים עַד הָעוֹלָם.`,
    francais: `Chant des montées, de David. Voici, qu'il est bon et agréable pour des frères de demeurer ensemble ! C'est comme l'huile précieuse qui descend sur la tête, qui descend sur la barbe d'Aaron. C'est comme la rosée du Hermon, qui descend sur les montagnes de Sion. Car c'est là que l'Éternel a ordonné la bénédiction, la vie pour l'éternité.`,
  },
  {
    numero: 134,
    titre: "Hiné Barkhou",
    hebreu: `שִׁיר הַמַּעֲלוֹת: הִנֵּה בָּרְכוּ אֶת יְהֹוָה כׇּל עַבְדֵי יְהֹוָה, הָעֹמְדִים בְּבֵית יְהֹוָה בַּלֵּילוֹת. שְׂאוּ יְדֵכֶם קֹדֶשׁ, וּבָרְכוּ אֶת יְהֹוָה. יְבָרֶכְךָ יְהֹוָה מִצִּיּוֹן, עֹשֵׂה שָׁמַיִם וָאָרֶץ.`,
    francais: `Chant des montées. Voici, bénissez l'Éternel, vous tous les serviteurs de l'Éternel, qui vous tenez dans la maison de l'Éternel pendant les nuits ! Levez vos mains vers le sanctuaire et bénissez l'Éternel ! Que l'Éternel te bénisse depuis Sion, Lui qui a fait les cieux et la terre.`,
  },
  {
    numero: 15,
    titre: "Mizmor LéDavid — Mi Yagour",
    hebreu: `מִזְמוֹר לְדָוִד: יְהֹוָה מִי יָגוּר בְּאׇהֳלֶךָ, מִי יִשְׁכֹּן בְּהַר קָדְשֶׁךָ. הוֹלֵךְ תָּמִים וּפֹעֵל צֶדֶק, וְדֹבֵר אֱמֶת בִּלְבָבוֹ. לֹא רָגַל עַל לְשֹׁנוֹ, לֹא עָשָׂה לְרֵעֵהוּ רָעָה, וְחֶרְפָּה לֹא נָשָׂא עַל קְרֹבוֹ. נִבְזֶה בְּעֵינָיו נִמְאָס, וְאֶת יִרְאֵי יְהֹוָה יְכַבֵּד, נִשְׁבַּע לְהָרַע וְלֹא יָמִר. כַּסְפּוֹ לֹא נָתַן בְּנֶשֶׁךְ, וְשֹׁחַד עַל נָקִי לֹא לָקָח. עֹשֵׂה אֵלֶּה לֹא יִמּוֹט לְעוֹלָם.`,
    francais: `Psaume de David. Éternel, qui séjournera dans Ta tente ? Qui demeurera sur Ta montagne sainte ? Celui qui marche dans l'intégrité, qui pratique la justice et dit la vérité dans son cœur. Celui qui ne calomnie pas, qui ne fait pas de tort à son prochain. Celui qui honore ceux qui craignent l'Éternel. Celui qui tient parole même à son détriment. Celui qui n'accepte pas de pot-de-vin contre l'innocent. Celui qui agit ainsi ne sera jamais ébranlé.`,
  },
  {
    numero: 1,
    titre: "Ashré HaIsh",
    hebreu: `אַשְׁרֵי הָאִישׁ אֲשֶׁר לֹא הָלַךְ בַּעֲצַת רְשָׁעִים, וּבְדֶרֶךְ חַטָּאִים לֹא עָמָד, וּבְמוֹשַׁב לֵצִים לֹא יָשָׁב. כִּי אִם בְּתוֹרַת יְהֹוָה חֶפְצוֹ, וּבְתוֹרָתוֹ יֶהְגֶּה יוֹמָם וָלָיְלָה. וְהָיָה כְּעֵץ שָׁתוּל עַל פַּלְגֵי מָיִם, אֲשֶׁר פִּרְיוֹ יִתֵּן בְּעִתּוֹ וְעָלֵהוּ לֹא יִבּוֹל, וְכֹל אֲשֶׁר יַעֲשֶׂה יַצְלִיחַ. לֹא כֵן הָרְשָׁעִים, כִּי כַמּוֹץ אֲשֶׁר תִּדְּפֶנּוּ רוּחַ. עַל כֵּן לֹא יָקֻמוּ רְשָׁעִים בַּמִּשְׁפָּט, וְחַטָּאִים בַּעֲדַת צַדִּיקִים. כִּי יוֹדֵעַ יְהֹוָה דֶּרֶךְ צַדִּיקִים, וְדֶרֶךְ רְשָׁעִים תֹּאבֵד.`,
    francais: `Heureux l'homme qui ne marche pas selon le conseil des méchants. Mais qui trouve son plaisir dans la Torah de l'Éternel, et la méditer jour et nuit. Il est comme un arbre planté près des cours d'eau, qui donne son fruit en sa saison ; tout ce qu'il entreprend réussit. Les méchants sont comme la paille emportée par le vent. C'est pourquoi les méchants ne subsisteront pas dans le jugement. Car l'Éternel connaît la voie des justes, et la voie des méchants se perdra.`,
  },
  {
    numero: 11,
    titre: "BaAdonaï Hassiti",
    hebreu: `לַמְנַצֵּחַ לְדָוִד: בַּיהֹוָה חָסִיתִי, אֵיךְ תֹּאמְרוּ לְנַפְשִׁי, נוּדִי הַרְכֶם צִפּוֹר. כִּי הִנֵּה הָרְשָׁעִים יִדְרְכוּן קֶשֶׁת, כּוֹנְנוּ חִצָּם עַל יֶתֶר, לִירוֹת בְּמוֹ אֹפֶל לְיִשְׁרֵי לֵב. כִּי הַשָּׁתוֹת יֵהָרֵסוּן, צַדִּיק מַה פָּעָל. יְהֹוָה בְּהֵיכַל קׇדְשׁוֹ, יְהֹוָה בַּשָּׁמַיִם כִּסְאוֹ, עֵינָיו יֶחֱזוּ, עַפְעַפָּיו יִבְחֲנוּ בְּנֵי אָדָם. יְהֹוָה צַדִּיק יִבְחָן, וְרָשָׁע וְאֹהֵב חָמָס שָׂנְאָה נַפְשׁוֹ. כִּי צַדִּיק יְהֹוָה צְדָקוֹת אָהֵב, יָשָׁר יֶחֱזוּ פָנֵימוֹ.`,
    francais: `Au chef des chantres, de David. Je me réfugie en l'Éternel ; comment me direz-vous : « Fuis dans les montagnes » ? Car les méchants bandent leur arc pour tirer dans l'ombre sur les hommes droits. L'Éternel est dans Son temple saint, l'Éternel a Son trône dans les cieux ; Ses yeux observent, Il éprouve les fils de l'homme. L'Éternel éprouve le juste, mais Son âme a en haine le méchant. Car l'Éternel est juste, Il aime la justice ; les hommes droits contemplent Sa face.`,
  },
  {
    numero: 12,
    titre: "Hoshia Adonaï",
    hebreu: `לַמְנַצֵּחַ עַל הַשְּׁמִינִית, מִזְמוֹר לְדָוִד: הוֹשִׁיעָה יְהֹוָה כִּי גָמַר חָסִיד, כִּי פַסּוּ אֱמוּנִים מִבְּנֵי אָדָם. שָׁוְא יְדַבְּרוּ אִישׁ אֶת רֵעֵהוּ, שְׂפַת חֲלָקוֹת בְּלֵב וָלֵב יְדַבֵּרוּ. יַכְרֵת יְהֹוָה כׇּל שִׂפְתֵי חֲלָקוֹת, לָשׁוֹן מְדַבֶּרֶת גְּדֹלוֹת. אֲשֶׁר אָמְרוּ לִלְשֹׁנֵנוּ נַגְבִּיר, שְׂפָתֵינוּ אִתָּנוּ, מִי אָדוֹן לָנוּ. מִשֹּׁד עֲנִיִּים מֵאֶנְקַת אֶבְיוֹנִים, עַתָּה אָקוּם יֹאמַר יְהֹוָה, אָשִׁית בְּיֵשַׁע יָפִיחַ לוֹ. אִמְרוֹת יְהֹוָה אֲמָרוֹת טְהֹרוֹת, כֶּסֶף צָרוּף בַּעֲלִיל לָאָרֶץ, מְזֻקָּק שִׁבְעָתָיִם. אַתָּה יְהֹוָה תִּשְׁמְרֵם, תִּצְּרֶנּוּ מִן הַדּוֹר זוּ לְעוֹלָם.`,
    francais: `Au chef des chantres, sur la harpe à huit cordes, psaume de David. Sauve, Éternel ! car les hommes pieux disparaissent, la fidélité s'efface parmi les fils de l'homme. On se dit des mensonges les uns aux autres, on parle avec des lèvres flatteuses et un cœur double. Que l'Éternel extermine toutes les lèvres flatteuses ! À cause de l'oppression des malheureux, l'Éternel dit : « Maintenant je me lève ». Les paroles de l'Éternel sont des paroles pures, un argent affiné, purifié sept fois. Toi, Éternel, Tu nous préserveras de cette génération à jamais.`,
  },
  {
    numero: 13,
    titre: "Ad Ana Adonaï",
    hebreu: `לַמְנַצֵּחַ מִזְמוֹר לְדָוִד: עַד אָנָה יְהֹוָה תִּשְׁכָּחֵנִי נֶצַח, עַד אָנָה תַּסְתִּיר אֶת פָּנֶיךָ מִמֶּנִּי. עַד אָנָה אָשִׁית עֵצוֹת בְּנַפְשִׁי, יָגוֹן בִּלְבָבִי יוֹמָם, עַד אָנָה יָרוּם אֹיְבִי עָלָי. הַבִּיטָה עֲנֵנִי יְהֹוָה אֱלֹהָי, הָאִירָה עֵינַי פֶּן אִישַׁן הַמָּוֶת. פֶּן יֹאמַר אֹיְבִי יְכׇלְתִּיו, צָרַי יָגִילוּ כִּי אֶמּוֹט. וַאֲנִי בְּחַסְדְּךָ בָטַחְתִּי, יָגֵל לִבִּי בִּישׁוּעָתֶךָ. אָשִׁירָה לַיהֹוָה, כִּי גָמַל עָלָי.`,
    francais: `Au chef des chantres, psaume de David. Jusqu'à quand, Éternel, m'oublieras-Tu toujours ? Jusqu'à quand me cacheras-Tu Ta face ? Jusqu'à quand mon ennemi s'élèvera-t-il sur moi ? Regarde, réponds-moi, Éternel mon Dieu ! Éclaire mes yeux, de peur que je ne m'endorme dans la mort. Mais moi, je me confie en Ta bonté ; mon cœur se réjouira de Ton salut. Je chanterai à l'Éternel, car Il m'a fait du bien.`,
  },
  {
    numero: 4,
    titre: "Békori Anéni",
    hebreu: `לַמְנַצֵּחַ בִּנְגִינוֹת מִזְמוֹר לְדָוִד: בְּקׇרְאִי עֲנֵנִי אֱלֹהֵי צִדְקִי, בַּצָּר הִרְחַבְתָּ לִּי, חׇנֵּנִי וּשְׁמַע תְּפִלָּתִי. בְּנֵי אִישׁ עַד מֶה כְבוֹדִי לִכְלִמָּה, תֶּאֱהָבוּן רִיק תְּבַקְשׁוּ כָזָב סֶלָה. וּדְעוּ כִּי הִפְלָה יְהֹוָה חָסִיד לוֹ, יְהֹוָה יִשְׁמַע בְּקׇרְאִי אֵלָיו. רִגְזוּ וְאַל תֶּחֱטָאוּ, אִמְרוּ בִלְבַבְכֶם עַל מִשְׁכַּבְכֶם וְדֹמּוּ סֶלָה. רַבִּים אֹמְרִים מִי יַרְאֵנוּ טוֹב, נְסָה עָלֵינוּ אוֹר פָּנֶיךָ יְהֹוָה. נָתַתָּה שִׂמְחָה בְלִבִּי, מֵעֵת דְּגָנָם וְתִירוֹשָׁם רָבּוּ. בְּשָׁלוֹם אֶשְׁכְּבָה וְאִישָׁנָה, כִּי אַתָּה יְהֹוָה לְבָדָד לָבֶטַח תּוֹשִׁיבֵנִי.`,
    francais: `Au chef des chantres, sur les instruments à cordes, psaume de David. Quand je crie, réponds-moi, Dieu de ma justice ! Dans la détresse, Tu m'as mis au large ; aie pitié de moi, écoute ma prière. Sachez que l'Éternel s'est choisi un homme pieux ; l'Éternel entend quand je crie vers Lui. Beaucoup disent : « Qui nous fera voir le bonheur ? » Fais luire sur nous la lumière de Ta face, Éternel ! Tu mets la joie dans mon cœur. Je me couche et m'endors en paix, car Toi seul, Éternel, Tu me donnes la sécurité.`,
  },
  {
    numero: 121,
    titre: "Chir LaMaalot — Essa Énaï",
    hebreu: `שִׁיר לַמַּעֲלוֹת: אֶשָּׂא עֵינַי אֶל הֶהָרִים, מֵאַיִן יָבֹא עֶזְרִי. עֶזְרִי מֵעִם יְהֹוָה, עֹשֵׂה שָׁמַיִם וָאָרֶץ. אַל יִתֵּן לַמּוֹט רַגְלֶךָ, אַל יָנוּם שֹׁמְרֶךָ. הִנֵּה לֹא יָנוּם וְלֹא יִישָׁן שׁוֹמֵר יִשְׂרָאֵל. יְהֹוָה שֹׁמְרֶךָ, יְהֹוָה צִלְּךָ עַל יַד יְמִינֶךָ. יוֹמָם הַשֶּׁמֶשׁ לֹא יַכֶּכָּה, וְיָרֵחַ בַּלָּיְלָה. יְהֹוָה יִשְׁמׇרְךָ מִכׇּל רָע, יִשְׁמֹר אֶת נַפְשֶׁךָ. יְהֹוָה יִשְׁמׇר צֵאתְךָ וּבוֹאֶךָ, מֵעַתָּה וְעַד עוֹלָם.`,
    francais: `Chant des montées. Je lève mes yeux vers les montagnes : d'où me viendra le secours ? Mon secours vient de l'Éternel, qui a fait les cieux et la terre. Il ne permettra pas que ton pied trébuche. L'Éternel est ton gardien, l'Éternel est ton ombre à ta droite. Le soleil ne te frappera pas le jour, ni la lune la nuit. L'Éternel te gardera de tout mal. L'Éternel gardera tes allées et venues, désormais et pour toujours.`,
  },
  {
    numero: 100,
    titre: "Mizmor LéToda",
    hebreu: `מִזְמוֹר לְתוֹדָה: הָרִיעוּ לַיהֹוָה כׇּל הָאָרֶץ. עִבְדוּ אֶת יְהֹוָה בְּשִׂמְחָה, בֹּאוּ לְפָנָיו בִּרְנָנָה. דְּעוּ כִּי יְהֹוָה הוּא אֱלֹהִים, הוּא עָשָׂנוּ וְלוֹ אֲנַחְנוּ, עַמּוֹ וְצֹאן מַרְעִיתוֹ. בֹּאוּ שְׁעָרָיו בְּתוֹדָה, חֲצֵרֹתָיו בִּתְהִלָּה, הוֹדוּ לוֹ בָּרְכוּ שְׁמוֹ. כִּי טוֹב יְהֹוָה, לְעוֹלָם חַסְדּוֹ, וְעַד דֹּר וָדֹר אֱמוּנָתוֹ.`,
    francais: `Psaume de reconnaissance. Acclamez l'Éternel, toute la terre ! Servez l'Éternel avec joie, venez devant Lui avec des chants d'allégresse. Sachez que l'Éternel est Dieu : c'est Lui qui nous a faits. Entrez dans Ses portes avec reconnaissance, bénissez Son Nom. Car l'Éternel est bon, Sa bonté dure toujours, et Sa fidélité de génération en génération.`,
  },
  {
    numero: 130,
    titre: "Shir HaMaalot — MiMaamakim",
    hebreu: `שִׁיר הַמַּעֲלוֹת: מִמַּעֲמַקִּים קְרָאתִיךָ יְהֹוָה. אֲדֹנָי שִׁמְעָה בְקוֹלִי, תִּהְיֶינָה אׇזְנֶיךָ קַשֻּׁבוֹת לְקוֹל תַּחֲנוּנָי. אִם עֲוֹנוֹת תִּשְׁמׇר יָהּ, אֲדֹנָי מִי יַעֲמֹד. כִּי עִמְּךָ הַסְּלִיחָה, לְמַעַן תִּוָּרֵא. קִוִּיתִי יְהֹוָה קִוְּתָה נַפְשִׁי, וְלִדְבָרוֹ הוֹחָלְתִּי. נַפְשִׁי לַאדֹנָי, מִשֹּׁמְרִים לַבֹּקֶר שֹׁמְרִים לַבֹּקֶר. יַחֵל יִשְׂרָאֵל אֶל יְהֹוָה, כִּי עִם יְהֹוָה הַחֶסֶד, וְהַרְבֵּה עִמּוֹ פְדוּת.`,
    francais: `Chant des montées. Des profondeurs je T'invoque, Éternel. Seigneur, écoute ma voix ; que Tes oreilles soient attentives à ma supplication. Mais le pardon est avec Toi, afin que l'on Te craigne. J'espère en l'Éternel, mon âme espère, et j'attends Sa parole. Mon âme attend le Seigneur plus que les gardes n'attendent le matin. Qu'Israël espère en l'Éternel ! Car la bonté est avec l'Éternel, et la rédemption abonde auprès de Lui.`,
  },
  {
    numero: 124,
    titre: "Shir HaMaalot — Loulé Adonaï",
    hebreu: `שִׁיר הַמַּעֲלוֹת לְדָוִד: לוּלֵי יְהֹוָה שֶׁהָיָה לָנוּ, יֹאמַר נָא יִשְׂרָאֵל. לוּלֵי יְהֹוָה שֶׁהָיָה לָנוּ, בְּקוּם עָלֵינוּ אָדָם. אֲזַי הַמַּיִם שְׁטָפוּנוּ, נַחְלָה עָבַר עַל נַפְשֵׁנוּ. אֲזַי עָבַר עַל נַפְשֵׁנוּ, הַמַּיִם הַזֵּידוֹנִים. בָּרוּךְ יְהֹוָה, שֶׁלֹּא נְתָנָנוּ טֶרֶף לְשִׁנֵּיהֶם. נַפְשֵׁנוּ כְּצִפּוֹר נִמְלְטָה מִפַּח יוֹקְשִׁים, הַפַּח נִשְׁבָּר וַאֲנַחְנוּ נִמְלָטְנוּ. עֶזְרֵנוּ בְּשֵׁם יְהֹוָה, עֹשֵׂה שָׁמַיִם וָאָרֶץ.`,
    francais: `Chant des montées, de David. Sans l'Éternel qui était pour nous, qu'Israël le dise ! Sans l'Éternel qui était pour nous, quand des hommes s'élevèrent contre nous, les eaux nous auraient submergés. Béni soit l'Éternel, qui ne nous a pas livrés en proie à leurs dents ! Notre âme s'est échappée comme l'oiseau du filet des oiseleurs ; le filet s'est rompu, et nous avons été délivrés. Notre secours est dans le Nom de l'Éternel, qui a fait les cieux et la terre.`,
  },
  {
    numero: 126,
    titre: "Shir HaMaalot — Béshouv Adonaï",
    hebreu: `שִׁיר הַמַּעֲלוֹת: בְּשׁוּב יְהֹוָה אֶת שִׁיבַת צִיּוֹן, הָיִינוּ כְּחֹלְמִים. אָז יִמָּלֵא שְׂחוֹק פִּינוּ וּלְשׁוֹנֵנוּ רִנָּה, אָז יֹאמְרוּ בַגּוֹיִם, הִגְדִּיל יְהֹוָה לַעֲשׂוֹת עִם אֵלֶּה. הִגְדִּיל יְהֹוָה לַעֲשׂוֹת עִמָּנוּ, הָיִינוּ שְׂמֵחִים. שׁוּבָה יְהֹוָה אֶת שְׁבִיתֵנוּ, כַּאֲפִיקִים בַּנֶּגֶב. הַזֹּרְעִים בְּדִמְעָה בְּרִנָּה יִקְצֹרוּ. הָלוֹךְ יֵלֵךְ וּבָכֹה נֹשֵׂא מֶשֶׁךְ הַזָּרַע, בֹּא יָבֹא בְרִנָּה נֹשֵׂא אֲלֻמֹּתָיו.`,
    francais: `Chant des montées. Quand l'Éternel ramena les captifs de Sion, nous étions comme dans un rêve. Alors notre bouche était remplie de rires, et notre langue de chants d'allégresse. Alors on disait parmi les nations : « L'Éternel a fait de grandes choses pour eux ». Ramène, Éternel, nos captifs, comme les torrents au désert. Ceux qui sèment avec larmes moissonneront avec chants d'allégresse. Celui qui marche en pleurant, portant la semence, revient avec joie, portant ses gerbes.`,
  },
  {
    numero: 19,
    titre: "Hashamayim Mésaprim",
    hebreu: `לַמְנַצֵּחַ מִזְמוֹר לְדָוִד: הַשָּׁמַיִם מְסַפְּרִים כְּבוֹד אֵל, וּמַעֲשֵׂה יָדָיו מַגִּיד הָרָקִיעַ. יוֹם לְיוֹם יַבִּיעַ אֹמֶר, וְלַיְלָה לְּלַיְלָה יְחַוֶּה דָּעַת. אֵין אֹמֶר וְאֵין דְּבָרִים, בְּלִי נִשְׁמָע קוֹלָם. תּוֹרַת יְהֹוָה תְּמִימָה מְשִׁיבַת נָפֶש, עֵדוּת יְהֹוָה נֶאֱמָנָה מַחְכִּימַת פֶּתִי. פִּקּוּדֵי יְהֹוָה יְשָׁרִים מְשַׂמְּחֵי לֵב, מִצְוַת יְהֹוָה בָּרָה מְאִירַת עֵינָיִם. יְהֹוָה צוּרִי וְגֹאֲלִי.`,
    francais: `Au chef des chantres, psaume de David. Les cieux racontent la gloire de Dieu, et le firmament proclame l'œuvre de Ses mains. Jour après jour ils parlent, nuit après nuit ils transmettent leur message, sans bruit ni paroles. La Torah de l'Éternel est parfaite, elle restaure l'âme ; le témoignage de l'Éternel est fidèle, il rend sage le simple. Les commandements de l'Éternel sont droits, ils réjouissent le cœur. Éternel, mon rocher et mon rédempteur.`,
  },
  {
    numero: 20,
    titre: "Yaankha Adonaï",
    hebreu: `לַמְנַצֵּחַ מִזְמוֹר לְדָוִד: יַעַנְךָ יְהֹוָה בְּיוֹם צָרָה, יְשַׂגֶּבְךָ שֵׁם אֱלֹהֵי יַעֲקֹב. יִשְׁלַח עֶזְרְךָ מִקֹּדֶש, וּמִצִּיּוֹן יִסְעָדֶךָּ. יִזְכֹּר כׇּל מִנְחֹתֶךָ, וְעוֹלָתְךָ יְדַשְּׁנֶה סֶלָה. יִתֶּן לְךָ כִלְבָבֶךָ, וְכׇל עֲצָתְךָ יְמַלֵּא. נְרַנְּנָה בִּישׁוּעָתֶךָ, וּבְשֵׁם אֱלֹהֵינוּ נִדְגֹּל. עַתָּה יָדַעְתִּי כִּי הוֹשִׁיעַ יְהֹוָה מְשִׁיחוֹ. יְהֹוָה הוֹשִׁיעָה, הַמֶּלֶךְ יַעֲנֵנוּ בְיוֹם קׇרְאֵנוּ.`,
    francais: `Au chef des chantres, psaume de David. Que l'Éternel te réponde au jour de la détresse, que le Nom du Dieu de Jacob te protège ! Qu'Il t'envoie du secours depuis le sanctuaire, et qu'Il te soutienne depuis Sion ! Qu'Il t'accorde ce que ton cœur désire, et qu'Il accomplisse tous tes projets ! Nous célébrerons ton salut, nous lèverons l'étendard au Nom de notre Dieu. Maintenant je sais que l'Éternel sauve Son messie. Éternel, sauve ! Que le Roi nous réponde au jour où nous L'invoquons.`,
  },
  {
    numero: 24,
    titre: "LaAdonaï HaAretz",
    hebreu: `לְדָוִד מִזְמוֹר: לַיהֹוָה הָאָרֶץ וּמְלוֹאָהּ, תֵּבֵל וְיֹשְׁבֵי בָהּ. כִּי הוּא עַל יַמִּים יְסָדָהּ, וְעַל נְהָרוֹת יְכוֹנְנֶהָ. מִי יַעֲלֶה בְהַר יְהֹוָה, וּמִי יָקוּם בִּמְקוֹם קׇדְשׁוֹ. נְקִי כַפַּיִם וּבַר לֵבָב, אֲשֶׁר לֹא נָשָׂא לַשָּׁוְא נַפְשִׁי. יִשָּׂא בְרָכָה מֵאֵת יְהֹוָה, וּצְדָקָה מֵאֱלֹהֵי יִשְׁעוֹ. שְׂאוּ שְׁעָרִים רָאשֵׁיכֶם, וְהִנָּשְׂאוּ פִּתְחֵי עוֹלָם, וְיָבוֹא מֶלֶךְ הַכָּבוֹד. יְהֹוָה צְבָאוֹת הוּא מֶלֶךְ הַכָּבוֹד סֶלָה.`,
    francais: `Psaume de David. À l'Éternel appartient la terre et tout ce qu'elle contient, le monde et ceux qui l'habitent. Qui montera à la montagne de l'Éternel ? Celui qui a les mains pures et le cœur sincère. Il recevra la bénédiction de l'Éternel, et la justice du Dieu de son salut. Portes, élevez vos linteaux ! Élevez-vous, portes éternelles ! Que le Roi de gloire fasse Son entrée. L'Éternel des armées, c'est Lui le Roi de gloire.`,
  },
  {
    numero: 29,
    titre: "Havou LéAdonaï",
    hebreu: `מִזְמוֹר לְדָוִד: הָבוּ לַיהֹוָה בְּנֵי אֵלִים, הָבוּ לַיהֹוָה כָּבוֹד וָעֹז. הָבוּ לַיהֹוָה כְּבוֹד שְׁמוֹ, הִשְׁתַּחֲווּ לַיהֹוָה בְּהַדְרַת קֹדֶש. קוֹל יְהֹוָה עַל הַמָּיִם, יְהֹוָה עַל מַיִם רַבִּים. קוֹל יְהֹוָה בַּכֹּחַ, קוֹל יְהֹוָה בֶּהָדָר. יְהֹוָה לַמַּבּוּל יָשָׁב, וַיֵּשֶׁב יְהֹוָה מֶלֶךְ לְעוֹלָם. יְהֹוָה עֹז לְעַמּוֹ יִתֵּן, יְהֹוָה יְבָרֵךְ אֶת עַמּוֹ בַשָּׁלוֹם.`,
    francais: `Psaume de David. Fils de Dieu, rendez à l'Éternel gloire et puissance ! Rendez à l'Éternel gloire pour Son Nom ! Prosternez-vous devant l'Éternel avec une sainte magnificence. La voix de l'Éternel est sur les eaux. La voix de l'Éternel est puissante, la voix de l'Éternel est majestueuse. L'Éternel siège comme Roi éternellement. L'Éternel donnera la force à Son peuple, l'Éternel bénira Son peuple par la paix.`,
  },
  {
    numero: 47,
    titre: "Kol HaAmim",
    hebreu: `לַמְנַצֵּחַ לִבְנֵי קֹרַח מִזְמוֹר: כׇּל הָעַמִּים תִּקְעוּ כָף, הָרִיעוּ לֵאלֹהִים בְּקוֹל רִנָּה. כִּי יְהֹוָה עֶלְיוֹן נוֹרָא, מֶלֶךְ גָּדוֹל עַל כׇּל הָאָרֶץ. יַדְבֵּר עַמִּים תַּחְתֵּינוּ, וּלְאֻמִּים תַּחַת רַגְלֵינוּ. עָלָה אֱלֹהִים בִּתְרוּעָה, יְהֹוָה בְּקוֹל שׁוֹפָר. זַמְּרוּ אֱלֹהִים זַמֵּרוּ, זַמְּרוּ לְמַלְכֵּנוּ זַמֵּרוּ. כִּי מֶלֶךְ כׇּל הָאָרֶץ אֱלֹהִים, זַמְּרוּ מַשְׂכִּיל. מָלַךְ אֱלֹהִים עַל גּוֹיִם, אֱלֹהִים יָשַׁב עַל כִּסֵּא קׇדְשׁוֹ.`,
    francais: `Au chef des chantres, des fils de Coré, psaume. Vous tous les peuples, battez des mains ! Poussez vers Dieu des cris de joie ! Car l'Éternel, le Très-Haut, est redoutable, Il est le grand Roi de toute la terre. Dieu monte au milieu des acclamations, l'Éternel s'élève au son de la trompette. Chantez à Dieu, chantez ! Chantez à notre Roi, chantez ! Car Dieu est le Roi de toute la terre. Dieu règne sur les nations, Dieu siège sur Son trône saint.`,
  },
  {
    numero: 93,
    titre: "Adonaï Malakh",
    hebreu: `יְהֹוָה מָלָךְ גֵּאוּת לָבֵשׁ, לָבֵשׁ יְהֹוָה עֹז הִתְאַזָּר, אַף תִּכּוֹן תֵּבֵל בַּל תִּמּוֹט. נָכוֹן כִּסְאֲךָ מֵאָז, מֵעוֹלָם אָתָּה. נָשְׂאוּ נְהָרוֹת יְהֹוָה, נָשְׂאוּ נְהָרוֹת קוֹלָם, יִשְׂאוּ נְהָרוֹת דׇּכְיָם. מִקֹּלוֹת מַיִם רַבִּים, אַדִּירִים מִשְׁבְּרֵי יָם, אַדִּיר בַּמָּרוֹם יְהֹוָה. עֵדֹתֶיךָ נֶאֶמְנוּ מְאֹד, לְבֵיתְךָ נָאֲוָה קֹדֶש, יְהֹוָה לְאֹרֶךְ יָמִים.`,
    francais: `L'Éternel règne, Il est revêtu de majesté ; l'Éternel est revêtu de puissance, Il S'en est ceint. Aussi le monde est ferme et ne chancelle pas. Ton trône est ferme dès les temps anciens ; Tu existes de toute éternité. Les fleuves élèvent leur voix, Éternel ! Plus puissant que les vagues de la mer, l'Éternel est puissant dans les hauteurs. Tes témoignages sont parfaitement certains ; la sainteté convient à Ta maison, ô Éternel, pour les jours sans fin.`,
  },
  {
    numero: 98,
    titre: "Mizmor — Shirou LéAdonaï",
    hebreu: `מִזְמוֹר: שִׁירוּ לַיהֹוָה שִׁיר חָדָש, כִּי נִפְלָאוֹת עָשָׂה, הוֹשִׁיעָה לּוֹ יְמִינוֹ וּזְרוֹעַ קׇדְשׁוֹ. הוֹדִיעַ יְהֹוָה יְשׁוּעָתוֹ, לְעֵינֵי הַגּוֹיִם גִּלָּה צִדְקָתוֹ. זָכַר חַסְדּוֹ וֶאֱמוּנָתוֹ לְבֵית יִשְׂרָאֵל, רָאוּ כׇל אַפְסֵי אָרֶץ אֵת יְשׁוּעַת אֱלֹהֵינוּ. הָרִיעוּ לַיהֹוָה כׇּל הָאָרֶץ, פִּצְחוּ וְרַנְּנוּ וְזַמֵּרוּ. יִרְעַם הַיָּם וּמְלֹאוֹ, תֵּבֵל וְיֹשְׁבֵי בָהּ. נְהָרוֹת יִמְחֲאוּ כָף, יַחַד הָרִים יְרַנֵּנוּ, לִפְנֵי יְהֹוָה כִּי בָא לִשְׁפֹּט הָאָרֶץ.`,
    francais: `Psaume. Chantez à l'Éternel un chant nouveau, car Il a fait des merveilles ; Sa droite et Son bras saint Lui ont assuré la victoire. L'Éternel a fait connaître Son salut, Il a révélé Sa justice aux yeux des nations. Il S'est souvenu de Sa bonté et de Sa fidélité envers la maison d'Israël. Acclamez l'Éternel, toute la terre ! Éclatez en chants de joie, chantez ! Que la mer retentisse, et tout ce qu'elle contient ! Que les fleuves battent des mains devant l'Éternel, car Il vient pour juger la terre.`,
  },
  {
    numero: 127,
    titre: "Shir HaMaalot LiShlomo",
    hebreu: `שִׁיר הַמַּעֲלוֹת לִשְׁלֹמֹה: אִם יְהֹוָה לֹא יִבְנֶה בַיִת, שָׁוְא עָמְלוּ בוֹנָיו בּוֹ, אִם יְהֹוָה לֹא יִשְׁמׇר עִיר, שָׁוְא שָׁקַד שׁוֹמֵר. שָׁוְא לָכֶם מַשְׂכִּימֵי קוּם מְאַחֲרֵי שֶׁבֶת, אֹכְלֵי לֶחֶם הָעֲצָבִים, כֵּן יִתֵּן לִידִידוֹ שֵׁנָא. הִנֵּה נַחֲלַת יְהֹוָה בָּנִים, שָׂכָר פְּרִי הַבָּטֶן. כְּחִצִּים בְּיַד גִּבּוֹר, כֵּן בְּנֵי הַנְּעוּרִים. אַשְׁרֵי הַגֶּבֶר אֲשֶׁר מִלֵּא אֶת אַשְׁפָּתוֹ מֵהֶם, לֹא יֵבֹשׁוּ כִּי יְדַבְּרוּ אֶת אוֹיְבִים בַּשָּׁעַר.`,
    francais: `Chant des montées, de Salomon. Si l'Éternel ne bâtit pas la maison, en vain travaillent ceux qui la bâtissent. Si l'Éternel ne garde pas la ville, en vain la sentinelle veille. En vain vous vous levez tôt et vous couchez tard ; l'Éternel donne du repos à celui qu'Il aime. Voici, les fils sont un héritage de l'Éternel, le fruit des entrailles est une récompense. Heureux l'homme qui en a rempli son carquois !`,
  },
  {
    numero: 128,
    titre: "Shir HaMaalot — Ashré Kol Yéré",
    hebreu: `שִׁיר הַמַּעֲלוֹת: אַשְׁרֵי כׇּל יְרֵא יְהֹוָה, הַהֹלֵךְ בִּדְרָכָיו. יְגִיעַ כַּפֶּיךָ כִּי תֹאכֵל, אַשְׁרֶיךָ וְטוֹב לָךְ. אֶשְׁתְּךָ כְּגֶפֶן פֹּרִיָּה, בְּיַרְכְּתֵי בֵיתֶךָ, בָּנֶיךָ כִּשְׁתִלֵי זֵיתִים סָבִיב לְשֻׁלְחָנֶךָ. הִנֵּה כִי כֵן יְבֹרַךְ גָּבֶר יְרֵא יְהֹוָה. יְבָרֶכְךָ יְהֹוָה מִצִּיּוֹן, וּרְאֵה בְּטוּב יְרוּשָׁלָיִם, כֹּל יְמֵי חַיֶּיךָ. וּרְאֵה בָנִים לְבָנֶיךָ, שָׁלוֹם עַל יִשְׂרָאֵל.`,
    francais: `Chant des montées. Heureux quiconque craint l'Éternel, qui marche dans Ses voies ! Tu jouis alors du travail de tes mains : heureux es-tu, et tout va bien pour toi ! Ta femme est comme une vigne féconde dans l'intérieur de ta maison ; tes fils sont comme des plants d'olivier autour de ta table. C'est ainsi qu'est béni l'homme qui craint l'Éternel. Que l'Éternel te bénisse depuis Sion, et puisses-tu voir le bonheur de Jérusalem tous les jours de ta vie !`,
  },
  {
    numero: 16,
    titre: "Mikhtam LéDavid",
    hebreu: `מִכְתָּם לְדָוִד: שָׁמְרֵנִי אֵל כִּי חָסִיתִי בָךְ. אָמַרְתְּ לַיהֹוָה אֲדֹנָי אָתָּה, טוֹבָתִי בַּל עָלֶיךָ. יְהֹוָה מְנָת חֶלְקִי וְכוֹסִי, אַתָּה תּוֹמִיךְ גּוֹרָלִי. אֲבָרֵךְ אֶת יְהֹוָה אֲשֶׁר יְעָצָנִי. שִׁוִּיתִי יְהֹוָה לְנֶגְדִּי תָמִיד, כִּי מִימִינִי בַּל אֶמּוֹט. לָכֵן שָׁמַח לִבִּי וַיָּגֶל כְּבוֹדִי, אַף בְּשָׂרִי יִשְׁכֹּן לָבֶטַח. כִּי לֹא תַעֲזֹב נַפְשִׁי לִשְׁאוֹל, לֹא תִתֵּן חֲסִידְךָ לִרְאוֹת שָׁחַת. תּוֹדִיעֵנִי אֹרַח חַיִּים, שֹׂבַע שְׂמָחוֹת אֶת פָּנֶיךָ, נְעִמוֹת בִּימִינְךָ נֶצַח.`,
    francais: `Hymne de David. Garde-moi, ô Dieu, car je m'abrite en Toi. Tu es mon Seigneur ; mon bonheur n'est qu'en Toi. L'Éternel est mon partage et ma coupe ; c'est Toi qui m'assures mon lot. Je bénis l'Éternel, mon conseiller. Je mets continuellement l'Éternel devant moi ; aussi je ne chancellerai pas. Tu ne livreras pas mon âme au séjour des morts. Tu me feras connaître le chemin de la vie ; il y a, dans Ta présence, une joie sans cesse renouvelée.`,
  },
  {
    numero: 138,
    titre: "Odekha LéDavid",
    hebreu: `לְדָוִד: אוֹדְךָ בְכׇל לִבִּי, נֶגֶד אֱלֹהִים אֲזַמְּרֶךָּ. אֶשְׁתַּחֲוֶה אֶל הֵיכַל קׇדְשְׁךָ, וְאוֹדֶה אֶת שְׁמֶךָ עַל חַסְדְּךָ וְעַל אֲמִתֶּךָ, כִּי הִגְדַּלְתָּ עַל כׇּל שִׁמְךָ אִמְרָתֶךָ. בְּיוֹם קָרָאתִי וַתַּעֲנֵנִי, תַּרְהִבֵנִי בְנַפְשִׁי עֹז. יוֹדוּךָ יְהֹוָה כׇּל מַלְכֵי אָרֶץ, כִּי שָׁמְעוּ אִמְרֵי פִיךָ. כִּי רָם יְהֹוָה וְשָׁפָל יִרְאֶה, וְגָבֹהַ מִמֶּרְחָק יְיֵדָּע. יְהֹוָה יִגְמֹר בַּעֲדִי, יְהֹוָה חַסְדְּךָ לְעוֹלָם, מַעֲשֵׂי יָדֶיךָ אַל תֶּרֶף.`,
    francais: `De David. Je Te louerai de tout mon cœur, je Te chanterai en présence de Dieu. Je me prosterne dans Ton temple saint, et je rends grâce à Ton Nom pour Ta bonté et Ta fidélité. Le jour où je T'ai invoqué, Tu m'as répondu, Tu m'as donné du courage. Tous les rois de la terre Te loueront, Éternel. Car l'Éternel est élevé, et Il regarde les humbles. L'Éternel achèvera ce qui me concerne ; Éternel, Ta bonté dure toujours ; n'abandonne pas l'œuvre de Tes mains.`,
  },
  {
    numero: 150,
    titre: "Hallélouya — Hallélou El BéKodsho",
    hebreu: `הַלְלוּיָה: הַלְלוּ אֵל בְּקׇדְשׁוֹ, הַלְלוּהוּ בִּרְקִיעַ עֻזּוֹ. הַלְלוּהוּ בִגְבוּרֹתָיו, הַלְלוּהוּ כְּרֹב גֻּדְלוֹ. הַלְלוּהוּ בְּתֵקַע שׁוֹפָר, הַלְלוּהוּ בְּנֵבֶל וְכִנּוֹר. הַלְלוּהוּ בְּתֹף וּמָחוֹל, הַלְלוּהוּ בְּמִנִּים וְעֻגָב. הַלְלוּהוּ בְּצִלְצְלֵי שָׁמַע, הַלְלוּהוּ בְּצִלְצְלֵי תְרוּעָה. כֹּל הַנְּשָׁמָה תְּהַלֵּל יָהּ, הַלְלוּיָה.`,
    francais: `Louez l'Éternel ! Louez Dieu dans Son sanctuaire ! Louez-Le dans le firmament de Sa puissance ! Louez-Le pour Ses œuvres puissantes ! Louez-Le au son de la trompette, louez-Le avec la harpe et la lyre ! Louez-Le avec le tambourin et la danse ! Louez-Le avec les cymbales sonores ! Que tout ce qui respire louange l'Éternel ! Louez l'Éternel !`,
  },
  {
    numero: 67,
    titre: "Élohim Yéhonénou",
    hebreu: `לַמְנַצֵּחַ בִּנְגִינֹת מִזְמוֹר שִׁיר: אֱלֹהִים יְחׇנֵּנוּ וִיבָרְכֵנוּ, יָאֵר פָּנָיו אִתָּנוּ סֶלָה. לָדַעַת בָּאָרֶץ דַּרְכֶּךָ, בְּכׇל גּוֹיִם יְשׁוּעָתֶךָ. יוֹדוּךָ עַמִּים אֱלֹהִים, יוֹדוּךָ עַמִּים כֻּלָּם. יִשְׂמְחוּ וִירַנְּנוּ לְאֻמִּים, כִּי תִשְׁפֹּט עַמִּים מִישֹׁר, וּלְאֻמִּים בָּאָרֶץ תַּנְחֵם סֶלָה. יוֹדוּךָ עַמִּים אֱלֹהִים, יוֹדוּךָ עַמִּים כֻּלָּם. אֶרֶץ נָתְנָה יְבוּלָהּ, יְבָרְכֵנוּ אֱלֹהִים אֱלֹהֵינוּ.`,
    francais: `Au chef des chantres, sur les instruments à cordes, psaume, chant. Que Dieu nous soit favorable et nous bénisse ! Qu'Il fasse luire sur nous Sa face ! Afin que l'on connaisse sur la terre Ta voie, et parmi toutes les nations Ton salut. Que les peuples Te louent, ô Dieu ! Que tous les peuples Te louent ! Que les nations se réjouissent ! Que la terre donne son fruit, que Dieu, notre Dieu, nous bénisse !`,
  },
  {
    numero: 70,
    titre: "Élohim LéHatsiléni",
    hebreu: `לַמְנַצֵּחַ לְדָוִד לְהַזְכִּיר: אֱלֹהִים לְהַצִּילֵנִי, יְהֹוָה לְעֶזְרָתִי חוּשָׁה. יֵבֹשׁוּ וְיַחְפְּרוּ מְבַקְשֵׁי נַפְשִׁי, יִסֹּגוּ אָחוֹר וְיִכָּלְמוּ חֲפֵצֵי רָעָתִי. יָשׁוּבוּ עַל עֵקֶב בׇּשְׁתָּם, הָאֹמְרִים הֶאָח הֶאָח. יָשִׂישׂוּ וְיִשְׂמְחוּ בְּךָ כׇּל מְבַקְשֶׁיךָ, וְיֹאמְרוּ תָמִיד יִגְדַּל אֱלֹהִים, אֹהֲבֵי יְשׁוּעָתֶךָ. וַאֲנִי עָנִי וְאֶבְיוֹן, אֱלֹהִים חוּשָׁה לִּי, עֶזְרִי וּמְפַלְטִי אָתָּה, יְהֹוָה אַל תְּאַחַר.`,
    francais: `Au chef des chantres, de David, pour le souvenir. Hâte-toi, ô Dieu, de me délivrer ! Éternel, hâte-toi de me secourir ! Que ceux qui Te cherchent se réjouissent et soient dans l'allégresse en Toi ! Et qu'ils disent toujours : « Que Dieu soit glorifié », ceux qui aiment Ton salut ! Moi, je suis pauvre et indigent ; ô Dieu, hâte-toi en ma faveur ! Tu es mon secours et mon libérateur ; Éternel, ne tarde pas !`,
  },
  {
    numero: 96,
    titre: "Shirou LéAdonaï Shir Hadash",
    hebreu: `שִׁירוּ לַיהֹוָה שִׁיר חָדָש, שִׁירוּ לַיהֹוָה כׇּל הָאָרֶץ. שִׁירוּ לַיהֹוָה בָּרְכוּ שְׁמוֹ, בַּשְּׂרוּ מִיּוֹם לְיוֹם יְשׁוּעָתוֹ. סַפְּרוּ בַגּוֹיִם כְּבוֹדוֹ, בְּכׇל הָעַמִּים נִפְלְאוֹתָיו. כִּי גָדוֹל יְהֹוָה וּמְהֻלָּל מְאֹד, נוֹרָא הוּא עַל כׇּל אֱלֹהִים. יִשְׂמְחוּ הַשָּׁמַיִם וְתָגֵל הָאָרֶץ, יִרְעַם הַיָּם וּמְלֹאוֹ. כִּי בָא לִשְׁפֹּט הָאָרֶץ, יִשְׁפֹּט תֵּבֵל בְּצֶדֶק וְעַמִּים בֶּאֱמוּנָתוֹ.`,
    francais: `Chantez à l'Éternel un chant nouveau, chantez à l'Éternel, vous, habitants de toute la terre ! Annoncez de jour en jour Son salut. Racontez parmi les nations Sa gloire, parmi tous les peuples Ses merveilles. Car l'Éternel est grand et digne de toute louange. Que les cieux se réjouissent et que la terre soit dans l'allégresse ! Que la mer retentisse, et tout ce qu'elle contient ! Car Il vient pour juger la terre, Il jugera le monde avec justice.`,
  },
];
