[build]
  command = "npm install && npm run build"
  publish = "build"
  base = "motskin02-pwa"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_PATHS = "node_modules,build/static/js"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
